- CONTRIBUTOR-LADDER.md
- CONTRIBUTOR-ROLES.md
These two files will document how to get involved in the project, what roles and responsibilities people can take on, and how to level up.
> Add contributor ladder and roles

- CiliumCon.md
Clarify how we pick CiliumCon co-chairs and other roles for the event
> CiliumCon roles

- ladder/members.yaml
I am reaching out to request that you kindly consider accepting my PR to join the Cilium project as an organization member. I have been actively contributing to the project and am excited to take the next step in becoming more involved. 
I look forward to working more closely with the Cilium team.
> Request to join Cilium project as an organization member

- ladder/members.yaml
I request to join as an organization member to Cilium project in accordance with https://github.com/cilium/community/blob/main/CONTRIBUTOR-LADDER.md#organization-member
My contributions beside reviews: https://github.com/cilium/cilium/pulls?q=is%3Aissue+author%3Adlapcevic+
I plan to continue contributing and be further involved in the project.
> Request to add dlapcevic to organization members

- ladder/members.yaml
I would love to become part of something extraordinary such as cilium project. I have been involved with cilium for some time and would be very happy to continue more.
> request to become an organization member

- Social-Guidelines.md
This PR updates the social media guidelines for the CIlium project
> update social guidelines

- CONTRIBUTORS.md
> Contributors file reference to code contributors

- ladder/members.yaml
add myself as part of the community team so I can help with the cilium ecosystem
> add liyi to the community

- ladder/teams/docs-structure.yaml
- ladder/teams/sig-hubble.yaml
- ladder/teams/tetragon.yaml
Adding myself to docs-structure, sig-hubble and tetragon teams.
> Add lambdanis as a reviewer

- ladder/members.yaml
It's a privilege to be a user and contributor to the Cilium project. I plan to continue to contribute.
My contributions: https://github.com/cilium/cilium/pulls?q=is%3Apr+author%3Ajaffcheng
> Request to add jaffcheng to organization members

- roles/Security-Team.md
Requesting to be added to this team – based on the description in the contributor roles document, I believe that I am already carrying out the responsibilities described for team members.
> Add Feroz Salam to security team

- ladder/teams/sig-bgp.yaml
I am getting out of touch with this part of the code so I am removing myself from review.
> Remove Dylan from BGP sig

- ladder/teams/operator.yaml
- ladder/teams/sig-servicemesh.yaml
I am getting out of touch with the service mesh part, but have worked a lot with the operator recently, so move the assignment accordingly.
> Remove myself from sig-servicemesh and join operator team

- ladder/teams/sig-clustermesh.yaml
I've been working with Clustermesh for a while now and it seems appropriate to add myself to the sig to help with reviews.
> Add myself to sig-clustermesh

- ladder/teams/ipcache.yaml
- ladder/teams/sig-policy.yaml
I haven't been keeping up with the latest developments in the area.
> Prune review assignments

- ladder/teams/build.yaml
- ladder/teams/ipsec.yaml
> adding myself to new teams

- ladder/members.yaml
Requesting to add myself in Cilium org members list, as I will continue to contribute to cilium community.
My contributions: 
PRs -  https://github.com/cilium/cilium/pulls?q=is%3Aopen%7Cclosed+is%3Apr+author%3Atamilmani1989
CFP - https://github.com/cilium/design-cfps/pulls?q=is%3Apr+author%3Atamilmani1989
Issues -  https://github.com/cilium/cilium/issues?q=is%3Aissue+is%3Aclosed%7Copen+tamilmani1989
> Request to add Tamilmani as org member

- ladder/members.yaml
As a member of the Community team frequently working on helping the Cilium ecosystem, I added myself to the Cilium org members list.
My contributions: https://github.com/cilium/cilium/pulls?q=is%3Aopen%7Cclosed+is%3Apr+author%3Avipul-21+
Issues I have contributed to: https://github.com/cilium/cilium/issues?q=is%3Aissue+is%3Aclosed%7Copen+vipul-21+
> Request to add organization member vipul-21

- ladder/teams/sig-clustermesh.yaml
I have been working on clustermesh for quite some time, reviewing PRs, debugging performance/scalability issues, and contributing to clustermesh.
> Add marseel to sig-clustermesh

- ladder/members.yaml
Requesting to add myself in Cilium org members list, as I will continue to contribute to cilium community.
PRs - https://github.com/cilium/cilium/pull/28700
> Request to add husnialhamdani as org member

- ladder/members.yaml
Requesting to add myself in Cilium org members list, as I will continue to contribute to cilium community.
PRs 10+  https://github.com/cilium/cilium/pulls?q=+is%3Apr+author%3Achaunceyjiang+
Issues - https://github.com/cilium/cilium/issues/created_by/chaunceyjiang
Issues -  https://github.com/cilium/cilium-cli/issues/created_by/chaunceyjiang
> Request to add chaunceyjiang as org member

- ladder/members.yaml
> Members: Add darox to list of members

- ladder/members.yaml
I've previously worked on the usecases  and  industry verticals on the cilium.io website
> add paularah to members list 

- ladder/members.yaml
Hello! :wave: 
I'm kindly requesting to be added as a Cilium org member as I would like to gain more autonomy on CI as per the contributor ladder.
I have made a few PRs (9 merged so far) already on various Cilium subcomponents: https://github.com/cilium/cilium/pulls/MrFreezeex and planning to continue doing more contributions in the future!
> members: add MrFreezeex as member

- ladder/members.yaml
Hey :wave: 
I'm requesting to join the Cilium organization. 
I made a few contribution around Hubble and I intend to continue working on it.
https://github.com/pulls?q=is%3Apr+author%3Aglrf+user%3Acilium
> members: add glrf as member

- ladder/members.yaml
I have worked on resolving multiple issues in tetragon project and continue to contribute more and climb the ladders in cilium community
here are my pr's currently 6 are merged and 5 are on the way
https://github.com/pulls?q=+is%3Apr+author%3Asadath-12+archived%3Afalse+tetragon
> member: add sadath-12

- ladder/members.yaml
Requesting to join cilium organization per https://github.com/cilium/community/blob/main/CONTRIBUTOR-LADDER.md#organization-member
Merged contributions:
* https://github.com/cilium/cilium/pull/28217
Open contributions:
* https://github.com/cilium/cilium/pull/29711
* https://github.com/cilium/cilium/pull/30648
I plan to continue contributing and be further involved in the project. Future contributions I'm planning include implementing follow-ups to BPF rate limiter PR that is currently open.
> Add siwiutki to organization members

- ladder/teams/egress-gateway.yaml
I have been working on egress gateway for some time, fixing some bugs and reviewing some PRs. I would like to contribute to make it even more awesome.
> Add ysksuzuki to egress-gateway team

- ladder/teams/ipsec.yaml
I know it's spelled IPsec, that must count for something.
> add myself to ipsec team

- ladder/teams/proxy.yaml
- ladder/teams/sig-agent.yaml
At the moment I'm focusing on other areas.
> Remove myself from sig-agent and proxy

- CONTRIBUTOR-LADDER.md
Label updates provide a lot of extra value & help to drive the development workflow.
> contributor-ladder: mention that reviewers can also modify labels

- CONTRIBUTOR-ROLES.md
- README.md
- Social-Guidelines.md
Added link from README to Governance page
Added link to Social Guidelines from community team section in Contributor Roles
Minor markdown linting
> docs: minor community docs improvements

- ladder/members.yaml
I request to be added to Cilium Organization as a member, as i am/will be contributing to Cilium. Thanks 
CFP: https://github.com/cilium/design-cfps/pull/29
PRs: https://github.com/cilium/cilium/pulls?q=is%3Aopen%7Cclosed+author%3Avakalapa
Issues: https://github.com/cilium/cilium/issues?q=is%3Aissue++author%3Avakalapa+
> Add vakalapa as organization member to Cilium

- ladder/members.yaml
I'm requesting to be added as a Cilium org member and intend to continue actively contributing to the community.
PRs: https://github.com/cilium/cilium/pulls?q=is%3Apr+author%3AanubhabMajumdar
CFP: https://github.com/cilium/cilium/issues/31666
Issues: https://github.com/cilium/cilium/issues?q=is%3Aopen%7Cclosed+is%3Aissue+author%3AanubhabMajumdar+
> Adding anubhabMajumdar as community member

- ladder/teams/vendor.yaml
Adding myself to the vendor team as we are currently lacking reviewers here.
> Add marseel to vendor team

- ladder/members.yaml
I'm applying for Cilium org membership.
Contributions:
* https://github.com/cilium/cilium/pull/31929
* https://github.com/cilium/cilium/pull/31903
* https://github.com/cilium/cilium/issues/31761
* https://github.com/cilium/cilium/pull/29489
* https://github.com/cilium/cilium/pull/29109
* https://github.com/cilium/cilium/pull/25942
I intend to continue my contributions to Cilium.
> Add jameslaverack as member

- ladder/teams/sig-datapath.yaml
I have been working on the datapath implementation for some time, e.g. loadbalancer, Egress GW. I would like to contribute to make it even more awesome.
> Add ysksuzuki to sig-datapath

- ladder/teams/cli.yaml
- ladder/teams/egress-gateway.yaml
- ladder/teams/proxy.yaml
* Removing myself from proxy, don't spend enough time involved with that so I'm not efficient with reviews, or I often have to defer to other reviewers.
* Adding myself to egressgateway as that's my current area of focus.
* Add myself to cli because I can be helpful there.
> ladder/teams: update my teams.

- ladder/teams/sig-hubble.yaml
I'm focusing on different projects now.
> Remove lambdanis from sig-hubble

- ladder/members.yaml
- ladder/teams/sig-agent.yaml
- ladder/teams/sig-bgp.yaml
I am transitioning to another project and will be unable to fulfill the responsibilities of an org member or reviewer. I enjoyed working on the project and wish you all the best.
> Ladder: Removes Daneyon Hansen

- ladder/members.yaml
Requesting to join cilium organization per https://github.com/cilium/community/blob/main/CONTRIBUTOR-LADDER.md#organization-member
Contributions:
CFP: https://github.com/cilium/cilium/issues/32576
PRs: https://github.com/cilium/cilium/pull/32055
https://github.com/cilium/cilium/pull/32501
https://github.com/cilium/cilium/pull/32574
I intend to continue my contributions to Cilium.
> Add ovidiutirla as member

- ladder/members.yaml
Sometimes I contribute to cilium, I want to have the oportunity to run tests
- https://github.com/cilium/cilium/pull/23712
- https://github.com/cilium/cilium/pull/27561
- https://github.com/cilium/cilium/pull/32730
> Add kvaps as member

- ladder/emeritus_members.yaml
It would be nice to recognize the efforts of people even after they have left the project
This takes over from #124
> Add file for Emeritus community members

- ladder/members.yaml
Would like to be able to rerun tests on https://github.com/cilium/cilium/pull/32678.
Also wrote https://github.com/cilium/design-cfps/pull/14 and have helped review https://github.com/cilium/cilium/pull/32185.
> Adding robscott to members

- ladder/teams/endpoint.yaml
I haven't been keeping up with the developments happening in the endpoint source code.
> Prune Aditi's review teams

- REPOSITORIES.md
Fix incorrect link to Repository Guidelines file
> chore: fix link

- REPOSITORIES.md
> add hubble-otel to the historical scope section of repositories

- REPOSITORY-GUIDELINES.md
Seems we forgot to add these originally so adding links to the issue templates now
> add links to issue templates

- ladder/members.yaml
Various contributions to projects in the Cilium GitHub group.
Examples:
- Cilium: https://github.com/cilium/cilium/issues?q=author%3Af1ko+
- Tetragon: https://github.com/cilium/tetragon/issues?q=author%3Af1ko+
> Add f1ko as member

- ladder/teams/egress-gateway.yaml
- ladder/teams/sig-lb.yaml
- ladder/teams/wireguard.yaml
Add myself to sig-lb and wireguard team, remove myself from egress-gateway team.
> ladder: Update Gray's teams

- ladder/members.yaml
I would like to be able to retrigger tests for my current and future PRs - https://github.com/cilium/cilium/pull/33306 https://github.com/cilium/cilium/pull/31735
I have contributed to multiple host firewall issues - https://github.com/cilium/cilium/issues/created_by/skmatti and PRs - https://github.com/cilium/cilium/pulls/skmatti
> Add skmatti to members

- ladder/teams/operator.yaml
Most of my contributions are in operator, including the big change for operator manages CIDs https://github.com/cilium/cilium/issues/27752
I want to and think it would be good to get involved more in the development of operator.
> Request to add dlapcevic to operator team

- ladder/members.yaml
I would like to enhance my ability to contribute to Cilium by becoming a member.
I have helped investigate and/or resolve multiple datapath issues, as well as contributed to policy correlation:
- https://github.com/cilium/cilium/issues?q=is%3Aissue+author%3Asypakine
cc @julianwiedmann
> Add sypakine (markstjohn) to members

- ladder/members.yaml
I would like to request to join Cilium project as an organization member in order to continue contributing more effectively.
Previous contributions:
- [PRs](https://github.com/cilium/cilium/pulls?q=is%3Apr+author%3Ajshr-w+)
- CFPs ([one](https://github.com/cilium/cilium/issues/32820#issuecomment-2285064494) and [two](https://github.com/cilium/design-cfps/pull/38))
> add jshr-w as an organization member

- ladder/members.yaml
Hi all --
I am starting on contributions with Cilium.
As background, I have been active in the general ecosystem on the K8s networking side.
I would like to be able to use the test automation (/ok-to-test) for contributions and reviews. 
*  https://github.com/cilium/cilium/pulls?q=is%3Apr+author%3Abowei
@joestringer
> Add bowei@ to cilium members

- ladder/teams/metrics.yaml
Hello! In the next couple of months, I've been tasked with working on some of the issues that we've been facing with metric stability and maturity. I'm planning on writing a CFP to propose a couple of new aspects for metric management. Some example issues that I'm hoping to address are:
* https://github.com/cilium/cilium/issues/27659
* https://github.com/cilium/cilium/issues/34521
* https://github.com/cilium/cilium/issues/27057
* https://github.com/cilium/cilium/issues/33995
Thanks!
> Request to add learnitall to metrics role

- ladder/members.yaml
Hi :wave: I recently joined and started to contribute on cilium/cilium and cilium/ebpf. I would like to be a member to contribute more effectively, have access to CI commands, and keep growing within this community.
So far, my contributions mainly involve:
* [cilium/cilium PRs](https://github.com/cilium/cilium/pulls?q=is%3Apr+author%3Asmagnani96+): small fixes to IPSEC, related doc, and cli.
* [cilium/ebpf PRs](https://github.com/cilium/ebpf/pulls?q=is%3Apr+author%3Asmagnani96+): add tcx example, ongoing `Map.Drain` api, and ongoing eBPF Variable api.
Thanks in advance, glad to provide further info :smiley:
> adding smagnani96 to org members

- roles/Maintainers.md
> roles/maintainers: fix formatting issues and clarify Hubble and Cilium CLI

- REPOSITORIES.md
> Move cilium/networkpolicy to historical

- REPOSITORIES.md
> Move cilium/chaos-testing-examples to historical

- ladder/teams/sig-foundations.yaml
Hey! 
In the past few months I've contributed to the sig-foundations area, and I would like to keep contributing and take the responsibility of a reviewer. 
Some of the contribution in this area:
https://github.com/cilium/hive/pulls?q=is%3Apr+is%3Aclosed+author%3Aovidiutirla
https://github.com/cilium/cilium/pulls?q=is%3Apr+author%3Aovidiutirla+
including some PR reviewers 
CFPs:
https://github.com/cilium/cilium/issues/33502
https://github.com/cilium/cilium/issues/34101
https://github.com/cilium/cilium/issues/34614
https://github.com/cilium/cilium/issues/34823
https://github.com/cilium/cilium/issues/34541
> Add ovidiutirla to sig-foundations

- ladder/teams/ci-structure.yaml
- ladder/teams/sig-policy.yaml
I'd like to focus more on work around policy and identity.
> Add myself to sig-policy, remove from ci-structure

- ladder/members.yaml
I will no longer contribute to the Cilium project.
My ongoing tasks will be continued by other people so I will keep them open:
1. https://github.com/cilium/cilium/pull/34484
2. https://github.com/cilium/design-cfps/pull/56 (also tracked as https://github.com/cilium/cilium/issues/34577)
> Remove AwesomePatrol from members list

- ladder/members.yaml
Add myself as an org member. These are some of my contributions over the last ~2 years, mainly for delegated IPAM and CNI:
https://github.com/cilium/cilium/pull/19219
https://github.com/cilium/cilium/pull/20630
https://github.com/cilium/cilium/pull/34839
https://github.com/cilium/cilium/pull/34870
https://github.com/cilium/cilium/pull/29063
> Add wedaly to organization members

- ladder/members.yaml
My PRs in the Hubble space:
https://github.com/cilium/cilium/pulls?q=is%3Aopen%7Cclosed+author%3Arectified95
https://github.com/cilium/cilium/pull/34325
https://github.com/cilium/cilium/pull/34849
https://github.com/cilium/cilium/pull/35058
https://github.com/cilium/cilium/pull/35185
> Add rectified95 as Cilium org member

- ladder/members.yaml
Add jrife to organization members.
> Add jrife to organization members

- ladder/members.yaml
- ladder/teams/build.yaml
- ladder/teams/tetragon.yaml
> Update William Findlay's GitHub username

- ladder/teams/ci-structure.yaml
- ladder/teams/helm.yaml
Adding myself to ci-structure and helm reviewer teams.
> feat: add artyop ci-structure & helm reviewers

- ladder/teams/fqdn.yaml
My past contributions to FQDN:
- https://github.com/cilium/cilium/pull/36252
- https://github.com/cilium/cilium/pull/35589
- https://github.com/cilium/cilium/pull/34941
- https://github.com/cilium/cilium/pull/34852
- https://github.com/cilium/cilium/pull/34175
- https://github.com/cilium/cilium/pull/34087
- https://github.com/cilium/cilium/pull/33989
- https://github.com/cilium/cilium/pull/27572
- https://github.com/cilium/cilium/pull/36255
I'm also planning to do some new year cleaning of the proxy and DNSZombie code. Finally, I'm also involved in discussions around the proposal for a standalone DNS proxy.
> fqdn: add bimmlerd

- SIG.md
- sig-TEMPLATE/README.md
- sig-TEMPLATE/charter.md
- sigs.yaml
Work around fomalizing SIGs, any feedback is greatly appreciated 🥹 
cc: @xmulligan
> SIG documentation

- ladder/teams/build.yaml
- ladder/teams/ipsec.yaml
I am no longer involved in those.
> Remove brb from ipsec and build

- ladder/members.yaml
I have made two contributions to cilium in last three months.
https://github.com/cilium/cilium/commit/439f5584cbb9470782fe3d936c84ffbc758386ad
https://github.com/cilium/cilium/commit/a89a36cfa6511d68c74471a04ec74213a90a8a77
> Add saiaunghlyanhtet to member

- ladder/teams/ci-structure.yaml
- ladder/teams/sig-agent.yaml
- ladder/teams/sig-policy.yaml
- ladder/teams/vendor.yaml
I have been busy with other works in servicemesh, and proxy team. Not to mention the maintenance works for cilium/proxy repo, so didn't have much time for ci-structure, sig-policy and vendor.
> teams: Remove myself from few teams

- ladder/teams/sig-clustermesh.yaml
I'm no longer actively involving ClusterMesh's development. Remove myself from the team.
> Remove Yutaro from sig-clustermesh

- ladder/members.yaml
👋 
I am opening this PR to request that I be added to the official list of Cilium Members.  It's my understanding that this grants me permission to kick off tests for future PRs of mine in the Cilium [repository](https://github.com/cilium/cilium).
Past contributions have been focused on the BGP Control Plane.
Thank you,
david.
- https://github.com/cilium/cilium/issues/37425
- https://github.com/cilium/cilium/issues/35721
- https://github.com/cilium/cilium/issues/34841
- https://github.com/cilium/cilium/issues/33163
- https://github.com/cilium/cilium/issues/32826
- https://github.com/cilium/cilium/issues/32693
- https://github.com/cilium/cilium/pull/36414
- https://github.com/cilium/cilium/pull/33307
- https://github.com/cilium/cilium/pull/33035
- …
> members: add David Swafford

- ladder/teams/pwru.yaml
We are lagging with pwru PR reviews. Hope this will help.
> Add new members to pwru team

- ladder/teams/github-sec.yaml
> teams: add artyop to github-sec reviewers

- ladder/teams/aws.yaml
- aws related issues:
https://github.com/cilium/cilium/issues/37975
https://github.com/cilium/cilium/issues/32052
https://github.com/cilium/cilium/issues/33654
- aws related PR
https://github.com/cilium/cilium/pull/38016
https://github.com/cilium/cilium/pull/37650
https://github.com/cilium/cilium/pull/37229
https://github.com/cilium/cilium/pull/36922
> teams: add liyihuang to aws reviewers

- ladder/members.yaml
I am Cilium contributor since 2020. I have several merged PRs in various area (e.g. CLI, CI, Datapath, Wireguard, K8S). And I will focus on the BGP area. Thanks for your trust.
My merged PRs:
[https://github.com/cilium/cilium/pull/24570](https://github.com/cilium/cilium/pull/24570)
[https://github.com/cilium/cilium/pull/24399](https://github.com/cilium/cilium/pull/24399)
[https://github.com/cilium/cilium/pull/24171](https://github.com/cilium/cilium/pull/24171)
[https://github.com/cilium/cilium/pull/22786](https://github.com/cilium/cilium/pull/22786)
[https://github.com/cilium/cilium/pull/20548](https://github.com/cilium/cilium/pull/20548)
[https://github.com/cilium/cilium/pull/16450](https://github.com/cilium/cilium/pull/16450)
[https://github.com/cilium/cilium/pull/16014](https://github.c …
> Add new member romanspb80

- ladder/members.yaml
Cilium contributor since October 2024 with 25+ PRs/issues, mostly working on Hubble and sometimes CI 😄
> members: add devodev as organization member

- ladder/teams/sig-hubble.yaml
I'd be happy to help with reviewing Hubble changes.
Contributions: https://github.com/cilium/cilium/issues?q=author%3Aglrf%20OR%20reviewed-by%3Aglrf%20
CC @kaworu 
CC @glibsm
> Add glrf to sig-hubble

- ladder/teams/sig-lb.yaml
Signed-off-by: Chris Tarazi <chris@isovalent.com>
> Remove myself from sig-lb

- ladder/members.yaml
Issues opened:
* https://github.com/cilium/cilium/issues/36425
* https://github.com/cilium/cilium/issues/36920
* https://github.com/cilium/cilium/issues/37056
PRs:
* Performance improvements:
* https://github.com/cilium/cilium/pull/36471
* https://github.com/cilium/cilium/pull/37430
* Dependencies upgrades:
* https://github.com/cilium/cilium/pull/36751
* https://github.com/cilium/cilium/pull/37098
* https://github.com/cilium/cilium/pull/37167
* And various other [misc PRs](https://github.com/cilium/cilium/pulls?q=is%3Apr+author%3AHadrienPatte)
> Add HadrienPatte as organization member

- ladder/members.yaml
- ladder/teams/tetragon.yaml
I have been raising PRs for compiling and porting tetragon project into Windows.
> Request to add exceptionaHandler to tetragon team and members group

- sig-scalability/README.md
- sig-scalability/charter.md
- sigs.yaml
Adding charter for SIG Scalability based on https://github.com/cilium/community/blob/main/sig-TEMPLATE/charter.md
> Add charter for SIG Scalability

- ladder/members.yaml
- ladder/teams/azure.yaml
I'm leaving AKS for another opportunity, so sadly I will no longer be working on Cilium.
> remove wedaly

- ladder/teams/sig-k8s.yaml
His expertise is clear; he should be sharing it :-p.
> ladder: add marseel to sig-k8s

- SIG.md
Adding links within the doc for easier reference, and correcting line break
> docs: tiny formatting changes

- sig-community/README.md
- sig-community/charter.md
- sigs.yaml
Idea for new SIG focused on growing the community, opening for further discussion
TODO:
> Add SIG Community Charter

- REPOSITORIES.md
https://github.com/cilium/arping
https://github.com/cilium/client-example
https://github.com/cilium/mock-hubble
https://github.com/cilium/stale-rules
https://github.com/cilium/state-writer
> Move archived repos to historical

- ladder/teams/tetragon.yaml
Add any other information or context for the reviewers
> tetragon: Request to add sayboras to tetragon

- CONTRIBUTOR-LADDER.md
See https://github.com/cilium/cilium/pull/27085 where the reviewing guide moved to a dedicated page
> Update reviewing guide link

- ladder/teams/fqdn.yaml
- ladder/teams/operator.yaml
As I'm focusing on ipam and egress-gateway
> Remove Fabio from fqdn and operator

- ladder/emeritus_members.yaml
- ladder/members.yaml
- ladder/teams/tetragon.yaml
Let me know if I need to make changes somewhere else - I just searched for my username.
> Remove lambdanis from the org

- ladder/members.yaml
Add parlakisik to members
Add any other information or context for the reviewers
> Add parlakisik to members

- ladder/members.yaml
Add any other information or context for the reviewers:
- I’m actively learning the internals of Cilium and focusing contributions around networking and observability.
- Looking to contribute more consistently to the Cilium datapath and service mesh components.
> members: add pillai-ashwin

- ladder/members.yaml
Hi :)
I've recently joined and started contributing primarily on cilium/cilium so far. Adding myself here so I can hopefully turn testing and fixes around quicker.
PRs by me:
https://github.com/cilium/cilium/pull/40684 - first change set to resolve some incorrect forwarding logic
https://github.com/cilium/cilium/pull/40577 - simple unit test bug fix when running on RHEL based platforms
I've also begun interaction with community PRs, eg:
https://github.com/cilium/cilium/pull/40559#issuecomment-3145068531
Let me know if I can add anything further to support this. :-)
> Add ajmmm to project members

- ladder/members.yaml
- https://github.com/cilium/cilium/issues/39646
- https://github.com/cilium/cilium/pull/40213
I am working on an implementation of Admin Network Policy for Cilium (see CFP and PR above). Becoming an org member would allow me to trigger the CI pipeline myself, speeding up the development.
> Add TheBeeZee to members
