CONTRIBUTORS.md
We appreciate the efforts of these community members who have been
researching the security posture of Cilium and raising discussions
with the project in order to improve Cilium's security footprint.
=> Extend CONTRIBUTORS.md with security researchers

CONTRIBUTOR-LADDER.md, CONTRIBUTOR-ROLES.md, roles/CI-Team.md, roles/Community-Team.md, roles/Maintainers.md, roles/Security-Team.md, roles/Triage-Team.md
This PR adds the contributor roles files and links them to the main doc. It covers everything in #4 except the member management file
=> add team roles files

CONTRIBUTORS.md
If contributors describe what they've been working on, we can potentially add links or otherwise help share their work. It also gives us a historical record so no-one thinks the project is "gaming" contributor numbers.
=> Describe contributions in commit message

roles/Security-Team.md
As discussed offline with multiple team members (e.g. Joe, Andre, and Jarno), I would love to submit the request to join the security team, I believe that this will help to fulfill my other responsibility as cilium/proxy maintainers for any security patches.
One point worth noting is that I have been maintaining and upgrading the cilium/proxy repo for any security patches for the last few months. Being part of the security team will definitely help with some preparation in advance.
https://github.com/cilium/community/blob/main/CONTRIBUTOR-ROLES.md#security-team
=> security-team: Add myself to security team

ladder/members.yaml
Per the contributor ladder document https://github.com/cilium/community/blob/main/CONTRIBUTOR-LADDER.md#organization-member I'd like to request membership in the org for myself, since I plan to contribute regularly, mainly in the areas related to Kubernetes where I'm sig-network and sig-testing member and Kind maintainer.
I've already contributed adding more test coverage for the Kubernetes integration to the project
- https://github.com/cilium/cilium/pull/25258
- https://github.com/cilium/cilium/pull/24209 
and fixing some bugs:
- https://github.com/cilium/cilium/pull/24202
- https://github.com/cilium/cilium/pull/24174 and helping to triage issues
=> Request org membership for aojea

ladder/members.yaml
Adds Daneyon Hansen as a Cilium member. I believe I have met the [outlined requirements](https://github.com/cilium/community/blob/main/CONTRIBUTOR-LADDER.md#organization-member) and look forward to my continued support of the project.
[Related PRs](https://github.com/cilium/cilium/pulls?q=is%3Apr+author%3Adanehans+)
[Related Issues](https://github.com/cilium/cilium/issues?q=is%3Aissue+author%3Adanehans)
=> Adds Daneyon Hansen as a Member

ladder/teams/sig-lb.yaml
I'd like to request you to add me as sig-lb reviewer. I have reviewed the following PRs related to the LB area.
add native tunnel encapsulation support for the XDP Loadbalancer
https://github.com/cilium/cilium/pull/24422
datapath: support Hybrid-DSR mode for Geneve dispatch
https://github.com/cilium/cilium/pull/25553
Also, I contributed to adding new LB feature.
Support DSR with Geneve dispatch
https://github.com/cilium/cilium/pull/23890
=> Request to add ysksuzuki as sig-lb reviewer

ladder/teams/docs-structure.yaml
Add docs-structure team and existing members to the repository. Some contributors have volunteered to join the team, this PR should make it easier for them to apply.
=> Add docs-structure team members

ladder/teams/docs-structure.yaml
I'd like to apply to be a part of the docs-structure team. I've been an organization member for about a year now and would like to start contributing to documentation tasks, as help was requested during the Cilium community meeting this week.
I've been an organization member for about a year now, since I joined Isovalent, and have focused on performance and scalability work in Cilium and Hubble, currently maintaining our performance automation repository [scaffolding](https://github.com/cilium/scaffolding). I'm quick to learn and would love to join the team to help out in any way I can with reviewing documentation PRs
Thank you!
=> Add learnitall to docs-structure

ladder/members.yaml
👋 
Ref. the contributor ladder, I'm nominating myself as a member so that I can easier trigger testing on my PRs, without having to bother the rest of you!
I've mostly been doing, and plan to continue, do scaleability work; https://github.com/cilium/cilium/issues?q=commenter%3Aodinuge
So far I've fixed a handful of scaling issues we have had internally, as well as reduced the memory usage of the agents with ~50% to 80% (in our biggest internal clusters). I've also fixed a few policy leaks and other perf stuff.
Thanks all!
=> Add odinuge to members

ladder/members.yaml
I request to join as an organization member to Cilium project in accordance with https://github.com/cilium/community/blob/main/CONTRIBUTOR-LADDER.md#organization-member
* Hubble field mask:
* https://github.com/cilium/cilium/pull/23198
* https://github.com/cilium/hubble/pull/1101
* misc:
* https://github.com/cilium/hubble-otel/pull/97
* https://github.com/cilium/hubble-otel/pull/96
* https://github.com/cilium/cilium/pull/21860
* in-progress:
* https://github.com/cilium/cilium/issues/25508
* https://github.com/cilium/cilium/pull/26379
* https://github.com/cilium/cilium/pull/26367
I plan to continue contributing and be further involved in the project, especially Hubble.
=> Add AwesomePatrol to organization members

CONTRIBUTOR-LADDER.md
To disambiguate from https://github.com/cilium/community/blob/main/roles/Maintainers.md
=> CONTRIBUTOR-LADDER.md: link to cilium's MAINTAINERS.md

roles/Security-Team.md
Varun has opted to step down from the team.
=> Remove Varun Marupadi from Cilium Security

ladder/members.yaml
As a member of the Community team frequently working on helping the Cilium ecosystem, I added myself to the Cilium org members list.
=> Add organization member tvonhacht-apple

ladder/teams/sig-bgp.yaml
I have been an [active contributor](https://github.com/cilium/cilium/pulls?q=is%3Apr+author%3Adanehans+) and [org member](https://github.com/cilium/community/blob/main/ladder/members.yaml) for the past 5 months with a focus on BGP Control Plane. I intend on continuing in this role and would like to be part of the `SIG-BGP` team.
=> SIG-BGP Team: Adds danehans

ladder/members.yaml
As a member of the Community team frequently working on helping the Cilium ecosystem, I added myself to the Cilium org members list.
=> add hacktivist123 to the org members list

ladder/teams/sig-agent.yaml
I have been an [active contributor](https://github.com/cilium/cilium/pulls?q=is%3Apr+author%3Adanehans+) and [org member](https://github.com/cilium/community/blob/main/ladder/members.yaml) for the past 5 months. Although I have mainly focused on the BGP Control Plane, I have contributed to other areas that fall under Cilium Agent, e.g. L2 announcer, node pkg, etc. I intend on continuing in this role and would like to be part of the `SIG-AGENT` team.
=> SIG-AGENT: Adds danehans

ladder/teams/sig-agent.yaml, ladder/teams/sig-datapath.yaml
Remove myself from these two very broad teams since it makes code review more complicated.
=> Remove lmb from sig-agent and sig-datapath

ladder/members.yaml
Requesting to add myself in Cilium org members list, as I will be able to trigger CI to better contribute to cilium community.
[ PRs for cilium ](https://github.com/cilium/cilium/pulls?q=is%3Apr+author%3Aweizhoublue+is%3Amerged+)
[ PRs for hubble-otel ](https://github.com/cilium/hubble-otel/pulls?q=is%3Apr+author%3AweizhouBlue+is%3Amerged)
[ Presetation in KCD China 2021: the network-acceleration secret of cilium ](https://www.bilibili.com/video/BV1Lq4y1372o/?spm_id_from=333.337.search-card.all.click)
[ blog: Interpretation of Cilium v1.12 : ServiceMesh is exciting ](https://blog.daocloud.io/8495.html)
=> add weizhoublue as a member

ladder/members.yaml
Requesting to join cilium organization per https://github.com/cilium/community/blob/main/CONTRIBUTOR-LADDER.md#organization-member
My contributions history:
* https://github.com/cilium/cilium/pull/22518
* https://github.com/cilium/cilium/pull/22731
* https://github.com/cilium/cilium/pull/23385
* https://github.com/cilium/cilium/pull/25582
* https://github.com/cilium/cilium/pull/25667
* https://github.com/cilium/cilium/pull/27350
* https://github.com/cilium/cilium/pull/27792
In progress contributions:
* https://github.com/cilium/cilium/pull/28873
* https://github.com/cilium/cilium/pull/27885 (currently marked as stale/closed as I was busy with other work but I plan toget back to it soon)
=> Add marqc as organization members

CONTRIBUTOR-LADDER.md, CONTRIBUTOR-ROLES.md, CiliumCon.md, GOVERNANCE.md, ladder/teams/egress-gateway.yaml
Looking at GOVERNANCE.md, there are two places where I stylistically modified the [original docs](https://docs.cilium.io/en/stable/community/governance/):
1. Line 82-83: add indentation for readability
2. Line 87: link to appropriate section on the page
Once this PR is merged, I will open a separate PR to update any governance links found in the Cilium repo as well as removing the governance docs from there
=> Issue 78 - move governance to the community repo

ADMINS-FOR-CILIUM.md
This is what I have found so far for tools based on [Istio's tools](https://github.com/istio/community/blob/master/ADMINS-FOR-ISTIO.md). All of the 'Google' tools I am assuming we have, but we may not use all of them. I have put @xmulligan as the owner for all the website tools as he seems to be the most active in that repo, but I am not sure if he actually is the right point of contact.
=> #89 - Document tool admins

GOVERNANCE.md
Initial work so far focuses on clarifying what is already written and applying principles found in the [Cilium Documentation Style Guide](https://docs.cilium.io/en/stable/contributing/docs/docsstyle/).
=> Editorial changes to governance docs

GOVERNANCE.md
In a handful of places this doc used the CNCF term "maintainer" where it really meant "committer" in Cilium terminology
=> docs: consistent terminology

ladder/teams/release-managers.yaml
This team handles publishing Cilium releases.
Ref: https://github.com/orgs/cilium/teams/release-managers
=> Add release-managers team members

CONTRIBUTOR-LADDER.md
This follows a discussion in the Committers channel about how (would-be) contributors sometimes have unreasonable expectations on how quickly (and how) the project should respond to their ideas
=> docs: add general guidance on contributor expectations

GOVERNANCE.md
The following clarifications were made:
- voluntary retirement of a committer
- editorial changes vs. material changes
- off-boarding steps 
Fixes: #90
=> Clarification of current governance practices

CONTRIBUTOR-LADDER.md
Mostly light edits, including some style changes, sentence rewording, consistent use of names and terms, and adding links where they could be helpful.
Areas that need particular focus:
- Line 22: I am extrapolating from the 'Inactive Members' section, and assuming the 6 months apply to only Reviewers and Committers. Just want to confirm that what I have written is correct!
- Line 77: I have removed 'Reviewed PRs' as a qualification, as I figured it was redundant given that 'Written and/or reviewed PRs' is already listed
=> editorial changes for contributor ladder

ladder/members.yaml, ladder/teams/hubble-ui.yaml
I request to be added to Cilium Organization as a member, as I am/will be contributing to it, especially on Hubble UI. Here are my contributions:
- [Remove wrong key lookup for service name in k8s labels](https://github.com/cilium/hubble-ui/pull/828) 
- [Remove precommit hook](https://github.com/cilium/hubble-ui/pull/801) 
- [E2E test case: test partially dropped flows](https://github.com/cilium/hubble-ui/pull/800) 
- [Check lint in PRs](https://github.com/cilium/hubble-ui/pull/791) 
- [Service map page: remove unnecessary scroll](https://github.com/cilium/hubble-ui/pull/784) 
- [Welcome screen: Allow scroll when namespaces list overflow](https://github.com/cilium/hubble-ui/pull/783)
=> Add yannikmesserli as a contributor to Hubble UI

.github/ISSUE_TEMPLATE/change-of-scope.yaml, .github/ISSUE_TEMPLATE/new-repository.yaml, REPOSITORIES.md, REPOSITORY-GUIDELINES.md
This PR adds the following four files:
**1. REPOSITORY-GUIDELINES.md** 
- definitions of the 5 scopes
- repository lifecycle info, including the process of adding new repositories (addresses #82) and change of scope / archival
**2. REPOSITORIES.md** 
- list of all repositories in the Cilium organization, sorted by scope
**3. .github/new-repository.yaml**
- issue form template for adding a new repository
**4. .github/change-of-scope.yaml**
- issue form template for changing the scope (includes archival) of an existing repository
Fixes: https://github.com/cilium/community/issues/27, https://github.com/cilium/community/issues/82
=> Add repository guidelines and list of repositories 

VALUES.md
The values document lays out how Cilium works together as a project. For people new to the project, it should guide them as the best way to engage with the project (for example jumping in to solve their issues rather than waiting for it to be assigned to them) and for existing contributors it should help guide choices when ways of working need to be decided upon (for example should we implement this in eBPF)
=> Add Cilium Community Values

ladder/teams/helm.yaml, ladder/teams/metrics.yaml, ladder/teams/sig-clustermesh.yaml, ladder/teams/sig-k8s.yaml
There are more team members, who are having more knowledge and work on these components day by day.
=> tam: Leave helm, metrics, clustermesh and k8s teams

ladder/teams/sig-scalability.yaml
I've been working on Cilium scalability, mostly related to network policies:
- https://github.com/cilium/cilium/issues/31457
- https://github.com/cilium/cilium/issues/33360
I want to and think it would be good to get involved more in the development of these areas.
=> Request to add dlapcevic to sig-scalability

roles/CI-Team.md
Hey folks! I'd like to request membership in the CI team role. I've been working for the past couple of months with @brb to improve our CI Health dashboards and processes. It's been a lot of fun, and I'd like to make the responsibility a bit more official. Thanks!
=> Request to add learnitall to CI role

roles/Maintainers.md
Add links to GitHub teams and repositories to make it grep-friendly to find which teams maintain which repositories.
=> Format Maintainers.md

ladder/teams/ipsec.yaml, ladder/teams/sig-datapath.yaml, ladder/teams/sig-lb.yaml
I don't expect to have much time for technical reviews for Cilium in the foreseeable future. Removing myself from `ipsec`, `sig-datapath`, and `sig-lb` teams.
=> Update teams for Quentin

roles/Maintainers.md
I propose Chance Zibolski [^1] and Robin Hahling [^2] to be added to hubble-maintainers team [^3] to recognize and celebrate their tremendous contributions to Hubble subsystem and Cilium observability in general. The proposal is also based on my firm belief that it is advantageous to have more than one maintainer in both European and US time zones.
Qualifications [^4]:
> Demonstrates a broad knowledge of the project across multiple areas
Chance has already been helping hubble-maintainers team by driving Hubble CLI release process, and by improving the dependency management process [^5][^6][^7][^8]. Chance is very active on Cilium Slack to answer Hubble-related questions from the community, and reviewing pull requests and providing insightful feedback to CFPs. Chance has made many critical …
=> Add chancez and rolinh to hubble-maintainers team

ladder/members.yaml
Following contributions on the CI in cilium/cilium [(34372)](https://github.com/cilium/cilium/pull/34372) and the renovate fix on cilium/image-tools [(286)](https://github.com/cilium/image-tools/pull/286) I would like to be added to the org members in order to continue maintaining and improving the CI.
=> feat: add Artyop to organisation members

ladder/members.yaml
Add Damian Sawicki (@DamianSawicki) to org members to make it easier to test future (and ongoing) PRs.  [Contributions to date](https://github.com/cilium/cilium/pulls?q=is%3Apr+author%3ADamianSawicki).
=> Add DamianSawicki to organization members

CONTRIBUTOR-LADDER.md
A bit of a nitpick, but at first when I read the reviewer process I thought I needed to add myself to a team named "Reviewer". This commit is just to clarify the fact that you need two different specific review area teams for becoming reviewer.
=> refac: change reviewer process PR doc

ladder/teams/hubble-metrics.yaml
Listing new sig for the metrics portion of Hubble and adding myself as reviewer.
Related contributions: https://github.com/cilium/cilium/pulls/rectified95
=> add rectified95 to new hubble-metrics group

ladder/teams/api.yaml, ladder/teams/docs-structure.yaml, ladder/teams/metrics.yaml, ladder/teams/sig-scalability.yaml, ladder/teams/vendor.yaml, roles/CI-Team.md
I'm shifting gears in my career away from Cilium, and will, for at least the time being, no longer have the availability to perform the responsibilities required for the teams that I've been assigned to.
Thank you for letting me be a part of these teams, I've enjoyed my time on them! Maybe I can come back at some point, but for right now I think it's best if I'm removed, thanks.
=> teams: Remove learnitall from multiple teams

CONTRIBUTOR-LADDER.md
Commit ee7eea33e604d removed reference to one of the teams, but kept the
process as requiring membership in two teams. There is no such
requirement to be a reviewer in multiple teams, the other team was
intended to be the general "reviewer" group. Since we don't have a
dedicated file for all reviewers currently, we don't need to mention the
other team. Make the steps make sense.
=> ladder: Fix reviewer process

.github/workflows/team-updates.yaml, tools/aggregate_team_overrides.sh
This PR adds two files
1. a helper script in tools/ directory that will aggregate the directory of per-team yaml files into a single yaml file that can be processed by the team management tool.
2. A github workflow that will send a cross-repository workflow dispatch event to the private team-management repo. 
This PR should be committed prior to the related/inbound team-management repository PR that implments the workflow that will catch the cross-repo workflow dispatch event sent by the workflow here.
Until the team-management repo workflow is in place, this is effectively a noop, but the workflow should operate to completion and send an dispatch event, if the token and repository permissions have been setup adequately. So I'd like to get this committed and test to make sure it works …
=> Add team-management automation tooling to community repo

tools/aggregate_team_overrides.sh
Cornercase in the team yaml file processes I didn't catch.
Fix is to add an explict newline between team files in the aggregate, to ensure correct yaml syntax.
=> small fix to team aggregation tool to address file reading without newline at the end of file

ladder/teams/sig-hubble.yaml
Unfortunately I no longer have the cycles to review Hubble changes.
=> Remove myself from @cilium/sig-hubble

ladder/members.yaml
@antonipp and @mvisonneau have been contributing to the Cilium project for a while now. They've also been very active in sharing learnings with the community through multiple CiliumCon talks.
For ref, here are the contributions from [Maxime](https://github.com/cilium/cilium/pulls?q=is%3Apr+author%3Amvisonneau+is%3Amerged+) and [Anton](https://github.com/cilium/cilium/pulls?q=is%3Apr+author%3Aantonipp+is%3Amerged+)
=> Nominating antonipp and mvisonneau as org members

ladder/members.yaml
I would like to be an organization member to contribute more effectively, have access to CI commands, and keep growing within this community.
Previous contributions:
PRs: https://github.com/cilium/cilium/pulls?q=is%3Apr+author%3Ahaozhangami
=> Add haozhangami to organization members

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md
PR template for people requesting to become org members and reviewers to clarify what information is helpful when opening the PR
Supersedes #190 and #191
I’ve considered various approaches to formatting this but landed on the current one for simplicity. Initially, I thought about making this an issue template, but requiring contributors to open an issue before a PR felt unnecessarily complex and could lead to confusion.
For reference, #190 included an additional top section that I’ve since removed, as it added extra wording without providing new information beyond what’s already covered in the ladder.
I also explored creating multiple templates, but that seemed confusing too—contributors would need to know the correct URLs for each template. This solution isn’t perfect since it applies to …
=> Add PR template for moving up the contributor ladder

ladder/teams/ipsec.yaml, ladder/teams/sig-encryption.yaml, ladder/teams/wireguard.yaml
From the time I started contributing to the Cilium codebase, I've been focussing on both datapath and control plane for IPSec and Wireguard. As I plan to continue contributing to this area of expertise, I'd kindly ask to add myself to these teams, so that I can also provide my feedback and insights in reviews.
=> add smagnani96 to sig-encryption, wireguard, and ipsec

ladder/teams/egress-gateway.yaml, ladder/teams/loader.yaml, ladder/teams/sig-datapath.yaml
During the transition of backend tooling, we identified these members
who were in practice not part of the teams although the community repo
stated they are expected to provide reviews for the corresponding teams.
As far as I can tell they no longer primarily focus on Cilium in their
day-to-day development so I don't want to re-impose expectations for
reviews upon them unless they actively signal that they would like to
return to reviewer status for these teams. Thus, remove them for now.
@lmb, @markpash feel free to send a revert PR if you would like to
re-join these teams.
=> Remove inactive reviewers

CONTRIBUTOR-LADDER.md
Reduces duration of inactive member policy from 18 to 12 months
Based on the experience from K8s https://github.com/kubernetes/community/pull/7380
=> update org requirements to 12 months

ladder/members.yaml
These members were identified as having incorrect capitalization for
their usernames in the members file, as compared with their true
username on GitHub. Fix them so that the synchronization to the upstream
GitHub organization works correctly.
=> members: Fix capitalization for members

ladder/teams/azure.yaml
I have been working on integration of cilium in AKS/Azure and would like to volunteer for any work related to this area
=> add tamilmani1989 to azure group

roles/Security-Team.md
As discussed offline I am configuring CodeQL scanning for the Github repositories and require access to the Security role to triage the findings.
N/A
N/A
=> Add Kyle to Security team for CodeQL Scanning Access

ladder/teams/docs-structure.yaml
I'll be now working on different things and I don't have capacity for Cilium
contributions anymore, so removing myself from the cilium/docs-structure team.
I might be not fully up-to-date with the process and tooling, so please let me
know if I need to make other changes. Retaining permissions in the Tetragon
repo would be helpful for me, but if it's not possible, I'll be fine too. I
don't need anything else, and I would prefer to be removed from unnecessary
teams.
=> cleanup: Remove lambdanis from docs-structure

ladder/teams/alibabacloud.yaml, ladder/teams/ipcache.yaml, ladder/teams/sig-datapath.yaml, ladder/teams/sig-encryption.yaml, ladder/teams/sig-policy.yaml
Update my membership to more accurately reflect my involvement in different areas of the Cilium project.
Notable changes:
- @cilium/alibabacloud: Removing myself as I'm not familiar with this code.
- @cilium/sig-encryption: My role was more of a fallback here, I trust the newer members to uphold the quality.
I've shifted myself to "mentor" in a few teams to reflect that I am happy to step in and provide guidance as needed, but on a day-to-day basis I am typically contributing elsewhere. For the remaining teams, I'll remain on the regular rotation to help spread the review load.
=> teams: Update membership for joestringer

ladder/teams/vagrant.yaml
We removed vagrant as a tool from cilium/cilium quite some time ago, no
need to have a team to manage this area any more.
cc @cilium/vagrant
=> teams: Remove vagrant team

ladder/teams/ipcache.yaml, ladder/teams/sig-datapath.yaml, ladder/teams/sig-policy.yaml
The cilium/team-manager tool that parses these files expects that
mentors are also listed in the members field of the team. Fix up these
references.
Fixes: 036dd77a354c ("teams: Update membership for joestringer")
=> teams: Fix mentors syntax

ladder/teams/build.yaml, ladder/teams/vendor.yaml
* https://github.com/cilium/cilium/issues/40000
* https://github.com/cilium/cilium/pull/37716
* https://github.com/cilium/cilium/pull/38288
* https://github.com/cilium/cilium/pull/38322
* https://github.com/cilium/cilium/issues/39235
* https://github.com/cilium/cilium/pull/36751
* https://github.com/cilium/cilium/pull/37087
* Various depreciated libraries/methods updates (https://github.com/cilium/cilium/pull/37098, https://github.com/cilium/cilium/pull/37167, https://github.com/cilium/cilium/pull/39335, https://github.com/cilium/cilium/pull/39364)
Being reviewer would also be helpful for work on base images in the context of https://github.com/cilium/cilium/issues/40000 as it grants write privileges (see https://github.com/cilium/cilium/pull/39996#issuecomment-2971499742).
=> Add HadrienPatte to `build` and `vendor` teams

ladder/teams/release-managers.yaml
I have actively participated as a Release Manager for the Cilium project for more than two years. Adding myself to the `release-managers` team.
=> Add asauber to release-managers

ladder/members.yaml
Katie Meinders will soon be an active member of the Community team. She
contributes to community content, outreach, and open source engagement around
Cilium and related projects. Adding her to the members ensures she has the
appropriate access and visibility to collaborate on repositories like
cilium.io, and to participate in content and community-related reviews.
=> members: Add krmeinders to members

ladder/members.yaml
Dan is an active member of the Community team and regularly contributes to community content, outreach, and open source engagement around Cilium and related projects. This addition ensures they have the appropriate access and visibility for reviewing and collaborating on repositories like cilium.io.
cc @xmulligan
=> members: Add thebsdbox to members

CODEOWNERS, ladder/reviewers.yaml, ladder/teams/cilium-io.yaml
This PR adds the `cilium-io` team to manage reviews for the `cilium.io` repository. This dedicated group helps clarify ownership and streamline the review process. It ensures that the right people are notified for content and community-related updates.
cc @xmulligan
=> teams: Add cilium-io team for cilium.io repo reviews

ladder/members.yaml
This reverts commit a8001717823d31516666d4f1d895ab953c5fab2b.
I'm going to revert this since it didn't follow the process for adding members to the org https://github.com/cilium/community/blob/main/CONTRIBUTOR-LADDER.md#organization-member
=> Revert "members: Add thebsdbox to members"

ladder/members.yaml
Reverts cilium/community#275
I'm going to revert this since it didn't follow the process for adding members to the org https://github.com/cilium/community/blob/main/CONTRIBUTOR-LADDER.md#organization-member
=> Revert "members: Add krmeinders to members"

ladder/teams/release-managers.yaml
I've previously done patch releases and plan on doing so in the future. Being part of the release-manager team will allow me to help out other release managers with review.
https://github.com/cilium/release/issues?q=is%3Aissue%20state%3Aclosed%20author%3Abimmlerd
Note: I'm not a committer (yet?), if that's required that'll have to come first.
=> teams: add bimmlerd to release-managers

ladder/members.yaml
Add Marc Suñé (me) to the members.yaml file, just so that I can shortcut one reviewer RTT during PRs (launch /test) :).
=> ladder: add msune as member

ladder/reviewers.yaml, ladder/teams/sig-datapath.yaml
(Updated links to point to jrife)
- Attendee at last year's NA Cilium Dev Summit.
* @pchaigno suggested adding myself as a reviewer + sig-datapath member
* Occasional kernel contributor: [bpf](https://lore.kernel.org/bpf/?q=jordan+rife), [netdev](https://lore.kernel.org/netdev/?q=jordan+rife)
* [1](https://lore.kernel.org/netdev/20230821162616.640423-1-jrife@google.com/) [2](https://lore.kernel.org/netdev/20230921234642.1111903-1-jrife@google.com/T/#u) to make socketLB work with NFS+kernel sockets: https://github.com/cilium/cilium/issues/21541
* [1](https://lore.kernel.org/bpf/20250502161528.264630-1-jordan@jrife.io/),[2](https://lore.kernel.org/bpf/20250714180919.127192-1-jordan@jrife.io/) to make socket iterators better. Related: https://github.com/cilium/cilium/pull/38693
* …
=> Add jrife to sig-datapath

ladder/members.yaml
Add Kateryna Nezdolii as a member so that she can trigger CI and we can solicite reviews from her. While she has no Cilium contributions yet, her upstream Envoy contributions qualify her to contribute to cilium/proxy repository.
=> members: Add Kateryna
